version: "3.8"
services:
  db:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mylib
    ports:
      - '5432:5432'
  react-frontend:
    build:
      context: ./mylib-frontend
      dockerfile: Dockerfile
    image: mylib-react-frontend:latest
    ports:
      - 3000:3000
    env_file:
      - ./mylib-frontend/.env
  react-backend:
    build:
      context: ./mylib-backend
      dockerfile: Dockerfile
    image: mylib-react-backend:latest
    ports:
      - 8002:8002
    env_file:
      - ./mylib-backend/.env
    depends_on:
      - db