apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-ip
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    app: mylib-backend

apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-port
  name: backend-service-port
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      nodePort: 30008
  selector:
    app: mylib-backend