apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-ip
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres